export const CONSTANT = {
TIME: 60,
TABLET_SCREEN_SIZE: 750,
COMPUTER_SCREEN_SIZE: 1181,
FILMS_SCREEN_SMARTPHON: 5,
FILMS_SCREEN_COMPUTER: 12,
FILMS_SCREEN_TABLET: 8,
ADDING_SCREEN_COMPUTER: 3,
ADDING_SCREEN_TABLE: 2
}